# sabnzbdplus

from    ubuntu

run		apt-get install -y --no-install-recommends python-software-properties

run     add-apt-repository ppa:jcfp/ppa && apt-get update

run		apt-get install -y sabnzbdplus

#mount --bind remote_downloads_path
#volume	["/downloads"]

#add	sabnzbd.ini /root/.sabnzbd/

# sed /etc/default/sabnzbdplus
# USER= 
# HOST=
# PORT=
# EXTRAOPTS=

expose	9090

#cmd	service sabnzbdplus start ; tail -f /root/.sabnzbd/logs/sabnzbd.log
