# sabnzbdplus

from    ubuntu

run     apt-get install -y python-software-properties

run     add-apt-repository ppa:jcfp/ppa && apt-get update

run		apt-get install -y sabnzbdplus

#volume	["/downloads"]

#mount remote downloads path

#add	sabnzbd.ini

# echo "" > /etc/default/sabnzbdplus

#expose	9090

#cmd	service sabnzbdplus start
