# pico - http://pico.dev7studios.com
# A stupidly simple & blazing fast, flat file CMS

from	ubuntu

env		DEBIAN_FRONTEND noninteractive

run 	apt-get install -y git
run 	git clone https://github.com/gilbitron/Pico.git

#run	apt-get install -y nginx php5 php5-fpm

#volume /Pico/content

#expose 80

#cmd	service nginx start ; service php5-fpm start ; tail -f /var/log/nginx/error.log
