# piwigo http://piwigo.org/
# Piwigo is photo gallery software for the web, built by an active community of users and developers.

from ubuntu

run apt-get install -y wget
run wget http://piwigo.org/download/dlcounter.php?code=latest

# Dependencies
#Nginx
#MySQL 5
#PHP 5 (5.2 recommended)
#ImageMagick or GD
