# Hark
# Hark is your personal radio station. Podcasts. Radio. Revolutionized.
# https://github.com/joelhans/Hark

from	ubuntu

run	apt-get install -y python-software-properties

run	add-apt-repository ppa:chris-lea/node.js

run	apt-get update
run	apt-get install -q -y git

run	apt-get install -q -y nodejs

run	git clone https://github.com/joelhans/Hark.git
run	cd hark ; npm install

#expose	3000

#cmd	["node", "/hark/app.js"]
