#phpmyadmin

from	ubuntu

run		export DEBIAN_FRONTEND=noninteractive
env		DEBIAN_FRONTEND noninteractive

run		apt-get install -y --no-install-recommends install nginx phpmyadmin mcrypt libmcrypt-dev

#expose 80

#cmd nginx service start


