# spotweb

from    ubuntu

run     apt-get update
run     apt-get install -y -q git

# apt-get install mysql-server mysql-client php5-mysql

#run	sed -i "s/^;date.timezone =.*/date.timezone = Europe\/Amsterdam/" /etc/php5/*/php.ini

#run	mysql
#CREATE DATABASE spotweb;
#GRANT ALL PRIVILEGES ON spotweb.* TO "spotweb"@"localhost" IDENTIFIED BY "DB_Verander_Mij_!";
#\q

# http://localhost/spotweb/install.php

# /var/www/spotweb/dbsettings.inc.php

#crontab -e
#30 */4 * * * /usr/bin/php /var/www/spotweb/retrieve.php >> /var/log/spotweb 2>&1
#0 1 * * * { cd /var/www/spotweb/ && git pull && /usr/bin/php upgrade-db.php ; } > /var/log/spotweb-upgrade 2>&1
