#mysqld

from	ubuntu

run		apt-get install -y --no-install-recommends install phpmyadmin mysql-server mcrypt libmcrypt-dev

#add	mysql-listen.cnf /etc/mysql/conf.d/mysql-listen.cnf

cmd		/usr/bin/mysqld_safe
