# Tiny Tiny RSS
# Tiny Tiny RSS is an open source web-based news feed (RSS/Atom) reader and aggregator, 
# designed to allow you to read news from any location, 
# while feeling as close to a real desktop application as possible.

from	ubuntu

run	apt-get update

run	apt-get install -y mysql php5-fpm php5-mysql nginx
	#add php   JSON mbstring iconv CURL

run	apt-get install -q -y git

run	git clone https://github.com/gothfox/Tiny-Tiny-RSS.git

#expose	80

#cmd	["service", "nginx", "start"]
# service mysql start
# service tt-rss start
