# casperjs

from	ubuntu
run		apt-get update && apt-get install -y python-software-properties
run		add-apt-repository -y ppa:martin.malek/testing && apt-get update && apt-get -y install casperjs
run		apt-get install -y libfreetype6 libfontconfig

