# casperjs

from	ubuntu

env		DEBIAN_FRONTEND noninteractive

run		apt-get install -y --no-install-recommends python-software-properties

run		add-apt-repository -y ppa:martin.malek/testing && apt-get update

run		apt-get install -y casperjs libfreetype6 libfontconfig


