# LazyLibrarian is a program to follow authors and grab metadata for all your digital reading needs.

from	ubuntu

env		DEBIAN_FRONTEND noninteractive

run 	apt-get install -y git python
run 	git clone -b herman-rogers-merge https://github.com/DobyTang/LazyLibrarian.git

expose 	5299

cmd		cd LazyLibrarian ; python LazyLibrarian.py
