# Transcribt
# http://designbyjoel.com/transcribt/
# Use Transcribt to transcribe all that pesky audio, faster and privately.
# https://github.com/joelhans/Transcribt

from	ubuntu

run	apt-get update && apt-get install -q -y git rubygems

run	gem install middleman

run	git clone git://github.com/joelhans/Transcribt.git

#expose	3000

cmd	cd Transcribt/ ; middleman server


