#!/bin/bash

command -v docker > /dev/null || { echo "## please install docker" ; exit 1 ; }

command -v ssh > /dev/null || { echo "## please install ssh" ; exit 1 ; }

[ -f ~/.ssh/id_rsa.pub ] || { echo "## please use ssh-keygen to generate an ssh key" ; exit 1 ; }

IMAGENAME=pipelight

if sudo docker inspect $IMAGENAME 2>&1 | grep -q "No such image" ; then
	echo "## Couldn't find image $IMAGENAME, will attempt to build"
	curl https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/Dockerfile | sudo docker build -t "$IMAGENAME" -
fi

# sudo docker run pipelight echo "checkcheck" | grep "^checkcheck"
sudo docker build -t "$IMAGENAME" .

JOB=$(sudo docker run -d $IMAGENAME "`cat ~/.ssh/id_rsa.pub`")

IPADDR=$(sudo docker inspect $JOB | grep IPAd | awk -F'"' '{print $4}')

echo -e "image: $IMAGENAME container: $JOB accesible on ip: $IPADDR\n"

#Prefs.js
#user_pref("general.useragent.override","Mozilla/5.0 (Windows NT 6.1; WOW64; rv:22.0) Gecko/20100101 Firefox/22.0");

# $1 first param as query string? 
#e.g. http://atwar-game.com/play/
#test silverlight: http://bubblemark.com/silverlight2.html
#firefox default to about:plugins

remotecmd="export LIBGL_ALWAYS_INDIRECT=0"
#remotecmd+=" && export LIBGL_DEBUG=verbose"
#remotecmd+=" && glxinfo | grep OpenGL"
#remotecmd+=" && glxinfo | grep direct"
#remotecmd+=" && midori"
ssh -XC -t -c blowfish-cbc,arcfour -oStrictHostKeyChecking=no -oCheckHostIP=no docker@$IPADDR $remotecmd

sudo docker stop $JOB
