#!/bin/bash

command -v docker || exit 1

command -v ssh || exit 1

[ -f ~/.ssh/id_rsa.pub ] || { echo "please use ssh-keygen to generate an ssh key" ; exit 1 ; }

[ -f id_rsa.pub ] || cp ~/.ssh/id_rsa.pub .

IMAGENAME=pipelight

## if not docker image tagged pipelight exist
## create image pipelight

#sudo docker inspect $IMAGENAME 2>&1 | grep -q "No such image"
#if [ $? -eq 0 ];then
#  echo "#Couldn't find image $IMAGENAME, will attempt to build"
#  read -p "Press [Enter] key to continue"
#  curl https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/Dockerfile | docker build -t "$IMAGENAME" -
#fi

## check pipelight image
# sudo docker run pipelight echo "checkcheck" | grep "^checkcheck"

#cd ~/git/Dockerfiles/pipelight
#sudo docker build -t "$IMAGENAME" .

# rm id_rsa.pub

JOB=$(sudo docker run -d $IMAGENAME)

IPADDR=$(sudo docker inspect $JOB | grep IPAd | awk -F'"' '{print $4}')

echo -e "image: $IMAGENAME container: $JOB accesible on ip: $IPADDR\n"

#Prefs.js
#user_pref("general.useragent.override","Mozilla/5.0 (Windows NT 6.1; WOW64; rv:22.0) Gecko/20100101 Firefox/22.0");

# check about:plugins for pipelight
# test silverlight: http://bubblemark.com/silverlight2.html
# %1 first param as query string? e.g. http://atwar-game.com/play/

# export LIBGL_ALWAYS_INDIRECT=0 && firefox

ssh -X -oStrictHostKeyChecking=no -oCheckHostIP=no docker@$IPADDR firefox about:plugins

sudo docker stop $JOB
