#!/bin/bash

#command -v docker || exit 1

#command -v xpra || exit 1

#if ! -F ~/.ssh/id_rsa && ssh-keygen


IMAGENAME=pipelight

## if not docker image tagged pipelight exist
## create image pipelight

sudo docker inspect $IMAGENAME 2>&1 | grep -q "No such image"
if [ $? -eq 0 ];then
  echo "#Couldn't find image $IMAGENAME, will attempt to build"
  read -p "Press [Enter] key to continue"
  curl https://raw.github.com/Thermionix/Dockerfiles/master/pipelight/Dockerfile | docker build -t "$IMAGENAME" -
fi

## check pipelight image
# docker run pipelight echo "Ahoy Matey" | grep "^Ahoy"

cd ~/git/Dockerfiles/pipelight
sudo docker build -t "$IMAGENAME" .

JOB=$(sudo docker run -d $IMAGENAME)
#JOB=$(sudo docker run -d -i -t $IMAGENAME /bin/bash)
#PORT=$(sudo docker port $JOB 22)

IPADDR=$(sudo docker inspect $JOB | grep IPAd | awk -F'"' '{print $4}')
#IPAddress": "172.17.3.48"

#echo -e "image: $IMAGENAME container: $JOB accesible on port: $PORT\n"
echo -e "image: $IMAGENAME container: $JOB accesible on ip: $IPADDR\n"


sleep 5
PASS=$(sudo docker logs $JOB | grep -P -m 1 "^sshpass" | cut -f2 -d" ")
#DISPLAY=$(sudo docker logs $JOB | grep -P -m 1 "^display" | cut -f2 -d" ")

echo -e "attach with password: $PASS \n"
xpra attach ssh:docker@$IPADDR:8 --ssh="ssh -oStrictHostKeyChecking=no -oCheckHostIP=no"
# -p $PORT

## when firefox closed, kill docker container

echo -e "\nwill stop container: $JOB"
read -p "Press [Enter] key to continue"
sudo docker stop $JOB
